POST https://api.<hostname>/1.1/onboarding/task.json?flow_name=login HTTP/2.0
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:<version>) Gecko/20100101 Firefox/<version>
accept: */*
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate, br, zstd
content-type: application/json
content-length: 930
referer: https://<hostname>/
x-guest-token: <guest-token>
x-twitter-client-language: en
x-twitter-active-user: yes
x-client-transaction-id: <transaction-id>
origin: https://<hostname>
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
authorization: Bearer <authorization-token>
cookie: guest_id_marketing=<guest_id_marketing>
cookie: guest_id_ads=<guest_id_ads>
cookie: personalization_id="<personalization_id>"
cookie: night_mode=2
cookie: kdt=<kdt-token>
cookie: dnt=1
cookie: att=<att-token>
cookie: guest_id=<guest_id>
cookie: gt=<gt-token>
cookie: _twitter_sess=<session-data>
te: trailers

{
  "input_flow_data": {
    "flow_context": {
      "debug_overrides": {},
      "start_location": {
        "location": "splash_screen"
      }
    }
  },
  "subtask_versions": {
    "action_list": 2,
    "alert_dialog": 1,
    "app_download_cta": 1,
    "check_logged_in_account": 1,
    "choice_selection": 3,
    "contacts_live_sync_permission_prompt": 0,
    "cta": 7,
    "email_verification": 2,
    "end_flow": 1,
    "enter_date": 1,
    "enter_email": 2,
    "enter_password": 5,
    "enter_phone": 2,
    "enter_recaptcha": 1,
    "enter_text": 5,
    "enter_username": 2,
    "generic_urt": 3,
    "in_app_notification": 1,
    "interest_picker": 3,
    "js_instrumentation": 1,
    "menu_dialog": 1,
    "notifications_permission_prompt": 2,
    "open_account": 2,
    "open_home_timeline": 1,
    "open_link": 1,
    "phone_verification": 4,
    "privacy_options": 1,
    "security_key": 3,
    "select_avatar": 4,
    "select_banner": 2,
    "settings_list": 7,
    "show_code": 1,
    "sign_up": 2,
    "sign_up_review": 4,
    "tweet_selection_urt": 1,
    "update_users": 1,
    "upload_media": 1,
    "user_recommendations_list": 4,
    "user_recommendations_urt": 1,
    "wait_spinner": 3,
    "web_modal": 1
  }
}
