GET https://x.com/i/api/graphql/Yka-W8dz7RaEuQNkroPkYw/UserByScreenName?variables=%7B%22screen_name%22%3A%22amazlngnature%22%2C%22withSafetyModeUserFields%22%3Atrue%7D&features=%7B%22hidden_profile_subscriptions_enabled%22%3Atrue%2C%22rweb_tipjar_consumption_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22subscriptions_verification_info_is_identity_verified_enabled%22%3Atrue%2C%22subscriptions_verification_info_verified_since_enabled%22%3Atrue%2C%22highlights_tweets_tab_ui_enabled%22%3Atrue%2C%22responsive_web_twitter_article_notes_tab_enabled%22%3Atrue%2C%22subscriptions_feature_can_gift_premium%22%3Atrue%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%7D&fieldToggles=%7B%22withAuxiliaryUserLabels%22%3Afalse%7D HTTP/2.0
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
accept: */*
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate, br, zstd
referer: https://x.com/AMAZlNGNATURE
content-type: application/json
x-twitter-auth-type: OAuth2Session
x-csrf-token: [TOKEN]
x-twitter-client-language: fr
x-twitter-active-user: yes
x-client-transaction-id: [TRANSACTION_ID]
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
authorization: Bearer [BEARER_TOKEN]
cookie: guest_id_marketing=[COOKIE_VALUE]
cookie: guest_id_ads=[COOKIE_VALUE]
cookie: personalization_id=[COOKIE_VALUE]
cookie: night_mode=[COOKIE_VALUE]
cookie: g_state=[COOKIE_VALUE]
cookie: kdt=[COOKIE_VALUE]
cookie: dnt=1
cookie: guest_id=[COOKIE_VALUE]
cookie: twid=[COOKIE_VALUE]
cookie: ct0=[TOKEN]
cookie: auth_token=[TOKEN]
cookie: lang=fr
te: trailers
content-length: 0
