POST https://<hostname>/i/api/graphql/<queryId>/CreateTweet HTTP/2.0
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:<version>) Gecko/20100101 Firefox/<version>
accept: */*
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate, br, zstd
content-type: application/json
content-length: <content-length>
referer: https://<hostname>/home
x-client-uuid: <client-uuid>
x-twitter-auth-type: OAuth2Session
x-csrf-token: <csrf-token>
x-twitter-client-language: en
x-twitter-active-user: yes
x-client-transaction-id: <transaction-id>
origin: https://<hostname>
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
authorization: Bearer <authorization-token>
cookie: guest_id_marketing=<guest_id_marketing>
cookie: guest_id_ads=<guest_id_ads>
cookie: personalization_id="<personalization_id>"
cookie: night_mode=2
cookie: g_state={"i_l":0}
cookie: kdt=<kdt>
cookie: dnt=1
cookie: lang=en
cookie: att=<att>
cookie: guest_id=<guest_id>
cookie: twid=<twid>
cookie: ct0=<cto>
cookie: auth_token=<auth-token>
te: trailers

{
    "variables": {
        "tweet_text": "<tweet_text>",
        "dark_request": false,
        "media": {
            "media_entities": [],
            "possibly_sensitive": false
        },
        "semantic_annotation_ids": [],
        "disallowed_reply_options": null
    },
    "features": {
        "communities_web_enable_tweet_community_results_fetch": true,
        "c9s_tweet_anatomy_moderator_badge_enabled": true,
        "responsive_web_edit_tweet_api_enabled": true,
        "graphql_is_translatable_rweb_tweet_is_translatable_enabled": true,
        "view_counts_everywhere_api_enabled": true,
        "longform_notetweets_consumption_enabled": true,
        "responsive_web_twitter_article_tweet_consumption_enabled": true,
        "tweet_awards_web_tipping_enabled": false,
        "creator_subscriptions_quote_tweet_preview_enabled": false,
        "longform_notetweets_rich_text_read_enabled": true,
        "longform_notetweets_inline_media_enabled": true,
        "articles_preview_enabled": true,
        "rweb_video_timestamps_enabled": true,
        "rweb_tipjar_consumption_enabled": true,
        "responsive_web_graphql_exclude_directive_enabled": true,
        "verified_phone_label_enabled": false,
        "freedom_of_speech_not_reach_fetch_enabled": true,
        "standardized_nudges_misinfo": true,
        "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
        "responsive_web_graphql_skip_user_profile_image_extensions_enabled": false,
        "responsive_web_graphql_timeline_navigation_enabled": true,
        "responsive_web_enhance_cards_enabled": false
    },
    "queryId": "<queryId>"
}
